---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install CA certificates package
  ansible.builtin.package:
    name: ca-certificates
    state: present
  become: true

- name: Ensure certificates directory exists
  ansible.builtin.file:
    path: "{{ ca_certificates_directory }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  become: true

- name: Download certificates
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    owner: root
    group: root
    mode: 'u=rw,go=r'
    dest: "{{ ca_certificates_directory }}/{{ item.filename }}"
  loop: "{{ ca_certificates_download }}"
  become: true

- name: Install certificates
  ansible.builtin.command:
    cmd: "{{ ca_certificates_update_command }}"
  register: result
  changed_when: false
  failed_when: result.rc != 0
  become: true
