---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: List installed certificates
      ansible.builtin.shell: "openssl crl2pkcs7 -nocrl -certfile /etc/ssl/certs/ca-certificates.crt | openssl pkcs7 -print_certs -noout"
      register: output_debian
      when: ansible_os_family == 'Debian'

    - name: Verify installed certificates (from default list)
      ansible.builtin.assert:
        that:
          - "'CommisSign' in output_debian.stdout"
      when: ansible_os_family == 'Debian'

    - name: List installed certificates
      ansible.builtin.shell: "trust list"
      register: output_redhat
      when: ansible_os_family == 'RedHat'

    - name: Verify installed certificates (from default list)
      ansible.builtin.assert:
        that:
          - "'CommisSign' in output_redhat.stdout"
      when: ansible_os_family == 'RedHat'
